### PR TITLE
fix: conform pagemap extension to sequence protocol

### LINKED ISSUE #318: Xcode 16 beta build error
**Describe the bug 🐛**
Build with instantsearch-ios as a dependency fails on Xcode 16 beta

Errors:

```
Type 'PageMap<Item>' does not conform to protocol 'Sequence'
Type 'PageMap<Item>' does not conform to protocol 'BidirectionalCollection'
Type 'PageMap<Item>' does not conform to protocol 'Collection'
```
**To Reproduce 🔍**
1. Create new Project
2. Add instantsearch-ios as a package dependency
3. Build project

(Also possible to reproduce with Examples project in repo)

**Expected behavior 💭**
Build succeeds

**Screenshots 🖥**
Errors in PageMap.swift
PageMap Errors

**Environment:**
 - macOS Version 15.0 beta (24A5264n)
 - Xcode Version 16.0 beta (16A5171c)
 - instantsearch-ios Version 7.26.2

### PR DESCRIPTION
**Pull request by dhayab**
**Summary**

This PR updates a PageMap extension so that it conforms more closely to the Sequence protocol, which seems more restrictive with Xcode 16.

This also updates the CI to run tests on Xcode 16 and fixes a number of failing jobs.

**Result**

- project can be built on Xcode 16
- ci workflow works again

Fixes #318

### CODE REVIEW

**Review by Haroenv — COMMENTED** [review]
changes look reasonable and CI passes, so LGTM, but as I don't have enough experience I'll let @aallam do the actual approval

File: Sources/InstantSearchCore/Pagination/PageMap.swift [hunk 1]
```diff
@@ -82,8 +82,9 @@ struct PageMap<Item> {
 // MARK: SequenceType
 
 extension PageMap: Sequence {
-  public func makeIterator() -> IndexingIterator<PageMap> {
-    return IndexingIterator(_elements: self)
+  public func makeIterator() -> IndexingIterator<[Item?]> {
+    let elements = (self.startIndex..<self.endIndex).map { self[$0] }
+    return IndexingIterator(_elements: elements)
```
Comment (aallam) [inline Sources/InstantSearchCore/Pagination/PageMap.swift:87]: I believe this is making a copy of the list elements, which would work. In case of performance issues come up, it might be a good idea to use another approach.

**Review by aallam — APPROVED** [review]

File: Sources/InstantSearchCore/Pagination/PageMap.swift (hunk 1 above)
Comment (dhayab) [reply Sources/InstantSearchCore/Pagination/PageMap.swift:87]: Indeed, I see. I believe we can commit to it and monitor for customer feedback as you mentioned. Thanks for your review 🙇 !

Comment (abdelmagied94) [reply Sources/InstantSearchCore/Pagination/PageMap.swift:87]: @aallam I have created this PR to prevent page items copying with each iterator creation, improving performance.
