### PR TITLE
fix: Xcode 12 crash due to unsynchronised sequencer

### LINKED ISSUE #128: Unrecognized Selector Sent To Instance - Sequencer Class
I am using InstantSearch MultiIndex components and I am getting a crash that occurs every now and then. App crashes and returns  "unrecognized selector sent to instance" error. I set a breakpoint and see that it ends up crashing in the dismissOperation(withSeqNo seqNo: Int) function in the Sequencer class. When not setting a breakpoint, I also get the following error:

Thread. 3: EXC_BAD_ACCESS (code=1, address=0x18) in the cancelOperation(withSeqNo seqNo: Int) function in the Sequencer class.

In the view controller, I am using a MultiIndexSearcher, MultiIndexSearchConnector, MultiIndexHitsInteractor, and a MultiIndexHitsController to perform the search. I have a search controller to handle user input. I eliminated everything else in the viewcontroller except these Instant Search Components

The crash only happens about 1 in 8 times. It will work as expected for a couple of builds, and then will crash with the above error every now in then.

I am using iOS 14. I can provide additional details if needed.

### PR DESCRIPTION
**Pull request by VladislavFitz**
**Summary**

This PR refactor Sequencer implementation to make it thread-safe and to avoid crashes occurring in Xcode 12

Resolves #128

### CODE REVIEW

File: Tests/InstantSearchCoreTests/Unit/SequencerTest.swift [hunk 1]
```diff
@@ -179,39 +177,23 @@ class SequencerTest: XCTestCase {
...
 
+    // All slow operations must be cancelled as the seqNo of the fast operation is bigger than the seqNo of the slow operations
     XCTAssertEqual(slowOperations.filter { $0.isCancelled }.count, slowOperationsCount)
+    
+    // Fast operation shouldn't be cancelled
     XCTAssertFalse(fastOperation.isCancelled)
 
   }
-
-  func testPendingOperations() {
```
Comment (spinach) [inline Tests/InstantSearchCoreTests/Unit/SequencerTest.swift:196]: So I see we removed a test here. Is there a new test that we can write that would fail with the old sequencer code, but succeed with this new one (in a way, that reproduces the crash due to unsynchronised sequencer)

Comment (VladislavFitz) [reply Tests/InstantSearchCoreTests/Unit/SequencerTest.swift:196]: I removed the `hasPendingOperations: Bool` property and it test as it was used nowhere, but it's no problem to restore it.
The crash of the unsynchronized sequencer is `EXC_BAD_ACCESS`, so it happens at a random moment while accessing  `pendingOperations` property of the Sequencer with the existing tests while testing with Xcode 12.
I switched the Bitrise environment to Xcode 12, so the fact that the Bitrise check has passed shows that this crash doesn't happen anymore.

**Review by spinach — APPROVED** [review]

**Comment by VladislavFitz** [comment]
Added [load test](https://github.com/algolia/instantsearch-ios/blob/0d9123377d12fad0b0d4294b4ec3d3512cb3ca19/Tests/InstantSearchCoreTests/Unit/SequencerTest.swift#L221) that completely ruins the previous `Sequencer` implementation 💥
